// <auto-generated />
using Labb1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb1.Migrations
{
    [DbContext(typeof(BookDbContext))]
    partial class BookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb1.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Stephen King",
                            Description = "A scary book.",
                            Genre = "Horror",
                            IsAvailable = true,
                            Title = "The Shining",
                            Year = 1977
                        },
                        new
                        {
                            Id = 2,
                            Author = "David Baldacci",
                            Description = "It's about a winner.",
                            Genre = "Thriller",
                            IsAvailable = true,
                            Title = "The Winner",
                            Year = 1997
                        },
                        new
                        {
                            Id = 3,
                            Author = "A.A. Milne",
                            Description = "It's about a bear.",
                            Genre = "Children",
                            IsAvailable = false,
                            Title = "Winnie The Pooh",
                            Year = 1926
                        },
                        new
                        {
                            Id = 4,
                            Author = "Douglas Adams",
                            Description = "A funny book.",
                            Genre = "Science Fiction",
                            IsAvailable = false,
                            Title = "The Hitchhicker's Guide to the Galaxy",
                            Year = 1979
                        },
                        new
                        {
                            Id = 5,
                            Author = "J.R.R. Tolkien",
                            Description = "It's about a ring.",
                            Genre = "Fantasy",
                            IsAvailable = true,
                            Title = "The Lord of the Rings",
                            Year = 1954
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
